name: BuildCheckTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt update && sudo apt install -y libtinfo5
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
          version: 18-1
    - name: Cache Cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/
          target/
        key: ${{ runner.os }}-cache-cargo-${{ hashFiles('Cargo.lock') }}
    - name: Install nightly rustfmt
      run: rustup toolchain install nightly --allow-downgrade -c rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Check (clippy)
      run: make clippy
    - name: Run tests
      run: cargo test --verbose